service: planning-poker-websocket

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  
  environment:
    SESSIONS_TABLE: ${self:service}-sessions-${self:provider.stage}
    CONNECTIONS_TABLE: ${self:service}-connections-${self:provider.stage}

functions:
  websocketConnect:
    handler: serverless/websocket-handler.connect
    events:
      - websocket: $connect
      
  websocketDisconnect:
    handler: serverless/websocket-handler.disconnect
    events:
      - websocket: $disconnect
      
  websocketMessage:
    handler: serverless/websocket-handler.message
    events:
      - websocket: $default

  createSession:
    handler: serverless/http-handler.createSession
    events:
      - http:
          path: /api/sessions
          method: post
          cors: true
          
  getSession:
    handler: serverless/http-handler.getSession
    events:
      - http:
          path: /api/sessions/{sessionCode}
          method: get
          cors: true
          
  healthCheck:
    handler: serverless/http-handler.healthCheck
    events:
      - http:
          path: /api/health
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    websocketPort: 3001
    lambdaPort: 3003
